version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Strong@Passw0rd
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
volumes:
  db_data:
